# version: '3.3'
# services:
#   catalog-web:
#     build:
#       context: ./catalog
#     restart: always
#     ports:
#       - "10083:8082"
#     volumes:
#       - ./file-storage:/file-storage
#       - ./log:/log
#     env_file:
#       - .env
#     depends_on:
#       - catalog-db
#     networks:
#       - frontend-network
#       - backend-network
#   catalog-db:
#     image: postgres:14-alpine
#     ports:
#       - '15083:5432'
#     restart: 'no'
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=secret99
#     volumes:
#       - catalog-db:/var/lib/postgresql/data
#     networks:
#       - backend-network
#   order-web:
#     build:
#       context: ./order
#     restart: always
#     ports:
#       - "10084:8083"
#     volumes:
#       - ./file-storage:/file-storage
#       - ./log:/log
#     env_file:
#       - .env
#     depends_on:
#       - order-db
#     networks:
#       - frontend-network
#       - backend-network
#   order-db:
#     image: postgres:14-alpine
#     ports:
#       - '15084:5432'
#     restart: 'no'
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=secret99
#     volumes:
#       - order-db:/var/lib/postgresql/data
#     networks:
#       - backend-network
#   user-web:
#     build:
#       context: ./user
#     restart: always
#     ports:
#       - "10082:8081"
#     volumes:
#       - ./file-storage:/file-storage
#       - ./log:/log
#     env_file:
#       - .env
#     depends_on:
#       - user-db
#     networks:
#       - frontend-network
#       - backend-network
#   user-db:
#     image: postgres:14-alpine
#     ports:
#       - '15082:5432'
#     restart: 'no'
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=secret99
#     volumes:
#       - user-db:/var/lib/postgresql/data
#     networks:
#       - backend-network
#   frontend-web:
#     build:
#       context: ./frontend_webapp
#     restart: always
#     ports:
#       - "10085:8084"
#     networks:
#       - frontend-network
#       - backend-network
      
# volumes:
#   catalog-db:
#     driver: local
#   order-db:
#     driver: local
#   user-db:
#     driver: local

# networks:
#   frontend-network:
#     driver: bridge
#   backend-network:
#     driver: bridge
version: '3.8'
services:
  db:
    image: postgres:14-alpine
    ports:
      - '15001:5432'
    restart: 'no'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret99
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local